### PR TITLE
Created es_xx.json files

### PR DESCRIPTION
**Pull request by Haseck**
Add spanish translations

### CODE REVIEW

**Comment by YanisBft** [comment]
Thanks a lot for all this work! Though it would be awesome if you could replace the \u codes by the actual characters, they are supported

**Comment by Haseck** [comment]
Of course

**Comment by Haseck** [comment]
All ready

**Comment by YanisBft** [comment]
Thanks! Will merge in a few hours, and it will be available in the next update 👍

**Pull request merged**
